2022-05-08T20:38:53.920143+00:00 app[web.1]: return self.config(*args, **kwargs)
2022-05-08T20:38:53.920143+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/decouple.py", line 105, in __call__
2022-05-08T20:38:53.920143+00:00 app[web.1]: return self.get(*args, **kwargs)
2022-05-08T20:38:53.920144+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/decouple.py", line 90, in get
2022-05-08T20:38:53.920144+00:00 app[web.1]: raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
2022-05-08T20:38:53.920144+00:00 app[web.1]: decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
2022-05-08T20:38:53.920240+00:00 app[web.1]: [2022-05-08 20:38:53 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-05-08T20:38:53.991080+00:00 app[web.1]: [2022-05-08 20:38:53 +0000] [11] [ERROR] Exception in worker process
2022-05-08T20:38:53.991081+00:00 app[web.1]: Traceback (most recent call last):
2022-05-08T20:38:53.991082+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-05-08T20:38:53.991083+00:00 app[web.1]: worker.init_process()
2022-05-08T20:38:53.991083+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-05-08T20:38:53.991083+00:00 app[web.1]: self.load_wsgi()
2022-05-08T20:38:53.991083+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-05-08T20:38:53.991084+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-05-08T20:38:53.991084+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-05-08T20:38:53.991084+00:00 app[web.1]: self.callable = self.load()
2022-05-08T20:38:53.991085+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-05-08T20:38:53.991085+00:00 app[web.1]: return self.load_wsgiapp()
2022-05-08T20:38:53.991085+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-05-08T20:38:53.991085+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-05-08T20:38:53.991085+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
2022-05-08T20:38:53.991086+00:00 app[web.1]: mod = importlib.import_module(module)
2022-05-08T20:38:53.991086+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-05-08T20:38:53.991086+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-08T20:38:53.991086+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-05-08T20:38:53.991086+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-05-08T20:38:53.991087+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-05-08T20:38:53.991087+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2022-05-08T20:38:53.991089+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2022-05-08T20:38:53.991089+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-05-08T20:38:53.991089+00:00 app[web.1]: File "/app/house/wsgi.py", line 16, in <module>
2022-05-08T20:38:53.991090+00:00 app[web.1]: application = get_wsgi_application()
2022-05-08T20:38:53.991090+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2022-05-08T20:38:53.991094+00:00 app[web.1]: django.setup(set_prefix=False)
2022-05-08T20:38:53.991094+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
2022-05-08T20:38:53.991095+00:00 app[web.1]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2022-05-08T20:38:53.991095+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 87, in __getattr__
2022-05-08T20:38:53.991095+00:00 app[web.1]: self._setup(name)
2022-05-08T20:38:53.991095+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 74, in _setup
2022-05-08T20:38:53.991095+00:00 app[web.1]: self._wrapped = Settings(settings_module)
2022-05-08T20:38:53.991095+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 183, in __init__
2022-05-08T20:38:53.991096+00:00 app[web.1]: mod = importlib.import_module(self.SETTINGS_MODULE)
2022-05-08T20:38:53.991096+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-05-08T20:38:53.991096+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-08T20:38:53.991096+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-05-08T20:38:53.991096+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-05-08T20:38:53.991096+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-05-08T20:38:53.991097+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2022-05-08T20:38:53.991097+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2022-05-08T20:38:53.991097+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-05-08T20:38:53.991097+00:00 app[web.1]: File "/app/house/settings.py", line 28, in <module>
2022-05-08T20:38:53.991097+00:00 app[web.1]: SECRET_KEY = config('SECRET_KEY')
2022-05-08T20:38:53.991097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/decouple.py", line 243, in __call__
2022-05-08T20:38:53.991098+00:00 app[web.1]: return self.config(*args, **kwargs)
2022-05-08T20:38:53.991098+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/decouple.py", line 105, in __call__
2022-05-08T20:38:53.991098+00:00 app[web.1]: return self.get(*args, **kwargs)
2022-05-08T20:38:53.991098+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/decouple.py", line 90, in get
2022-05-08T20:38:53.991098+00:00 app[web.1]: raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
2022-05-08T20:38:53.991099+00:00 app[web.1]: decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
2022-05-08T20:38:53.991257+00:00 app[web.1]: [2022-05-08 20:38:53 +0000] [11] [INFO] Worker exiting (pid: 11)
2022-05-08T20:38:54.069029+00:00 app[web.1]: Traceback (most recent call last):
2022-05-08T20:38:54.069076+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
2022-05-08T20:38:54.069376+00:00 app[web.1]: self.sleep()
2022-05-08T20:38:54.069392+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
2022-05-08T20:38:54.069603+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2022-05-08T20:38:54.069617+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2022-05-08T20:38:54.069773+00:00 app[web.1]: self.reap_workers()
2022-05-08T20:38:54.069787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2022-05-08T20:38:54.070011+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2022-05-08T20:38:54.070097+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-05-08T20:38:54.070109+00:00 app[web.1]: 
2022-05-08T20:38:54.070110+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-05-08T20:38:54.070110+00:00 app[web.1]: 
2022-05-08T20:38:54.070123+00:00 app[web.1]: Traceback (most recent call last):
2022-05-08T20:38:54.070137+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2022-05-08T20:38:54.070244+00:00 app[web.1]: sys.exit(run())
2022-05-08T20:38:54.070257+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2022-05-08T20:38:54.070367+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2022-05-08T20:38:54.070380+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
2022-05-08T20:38:54.070534+00:00 app[web.1]: super().run()
2022-05-08T20:38:54.070548+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
2022-05-08T20:38:54.070672+00:00 app[web.1]: Arbiter(self).run()
2022-05-08T20:38:54.070685+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
2022-05-08T20:38:54.070843+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2022-05-08T20:38:54.070857+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
2022-05-08T20:38:54.071067+00:00 app[web.1]: self.stop()
2022-05-08T20:38:54.071081+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
2022-05-08T20:38:54.071295+00:00 app[web.1]: time.sleep(0.1)
2022-05-08T20:38:54.071310+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2022-05-08T20:38:54.071474+00:00 app[web.1]: self.reap_workers()
2022-05-08T20:38:54.071488+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2022-05-08T20:38:54.071731+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2022-05-08T20:38:54.071808+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-05-08T20:38:54.239658+00:00 heroku[web.1]: Process exited with status 1
2022-05-08T20:38:54.311465+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-08T20:39:02.254285+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=house-estat.herokuapp.com request_id=e4268226-cc63-41fa-9534-9ad529d0929a fwd="79.71.163.93" dyno= connect= service= status=503 bytes= protocol=https
2022-05-08T20:39:02.527991+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=house-estat.herokuapp.com request_id=598e7b4b-f2fd-4c84-9538-3fa1ac27ea86 fwd="79.71.163.93" dyno= connect= service= status=503 bytes= protocol=https
2022-05-08T20:39:43.404895+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=house-estat.herokuapp.com request_id=ba490d86-e45d-43f9-abff-f90af1bdf5c8 fwd="79.71.163.93" dyno= connect= service= status=503 bytes= protocol=https
2022-05-08T20:39:43.659751+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=house-estat.herokuapp.com request_id=b0358d27-bfed-48fe-9ae7-6c0c0e2abe9a fwd="79.71.163.93" dyno= connect= service= status=503 bytes= protocol=https
